version: '3'

services:
   db:
     container_name: "ut-matching_db"
     image: mysql:5.7
     ports:
       - 13306:3306     
     volumes:
      - ./db/backup1213:/var/lib/mysql
       - ./db/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - network_ut-matching

   wordpress: 
     container_name: "ut-matching-wp"
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     volumes:
       - ./wordpress/wp-content:/var/www/html/wp-content
      #  - ssh:/ssh
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
       - network_ut-matching

   phpmyadmin:
    container_name: "ut-matching_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network_ut-matching

networks:
  network_ut-matching:
    external: true

volumes:
  ssh:
    external: true
